### ISSUE TITLE
SAM Exclusion Search Web Service

### ISSUE THREAD

**Issue by rtnewday** [GSA/sam_api#114]
I am putting together requirements for setting up a client application and have a very high level question on sending the request string.

We are planning to use doSearch to do a partialName search and I would like to know if we are able to send multiple searches in the same string. We would like to search around six individuals.

For example, if I would like to search both John Smith and Jane Doe, would the search string be set up as follows?

<soapenv:Envelope 
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:sam="http://www.sam.gov"> 
  <soapenv:Header/> 
  <soapenv:Body> 
    <sam:doSearch> 
      <exclusionSearchCriteria> 
        <partialName>John Smith</partialName> 
      </exclusionSearchCriteria> 
    </sam:doSearch> 
    <sam:doSearch> 
      <exclusionSearchCriteria> 
        <partialName>Jane Doe</partialName> 
      </exclusionSearchCriteria> 
    </sam:doSearch> 
  </soapenv:Body> 
</soapenv:Envelope>

Or would we need to send a separate request for each individual? Any information would be greatly appreciated!

**Comment by aromero6** [comment]
Hi,

Unfortunately we require a separate request for each search.  We are not
configured to handle multiple searches per request.

Hope this answers your question.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Integrated Acquisition Environment
IT Operations Team
O: 312.353.3116
C: 312.497.5592

**Comment by rtnewday** [comment]
Thanks for the quick response!
