### ISSUE TITLE
api.data.gov/sam/v1/registrations/'

### ISSUE THREAD

**Issue by jeantsghjz** [GSA/sam_api#131]
could I have a code to apply on python please ?

**Comment by aromero6** [comment]
Hi,

Unfortunately, we do not provide code specific to an environment.  We can
help troubleshoot if there is an issue on our end, but cannot devote
resources for private or third party projects.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Integrated Acquisition Environment
IT Operations Team
O: 312.353.3116
C: 312.497.5592

**Comment by NicholeSalinger** [comment]
@jeantsghjz @aromero6 

I have been trying to piece together what the Python code would look like but have not gotten it all to work. I want the API call to go through a mutable list/dataframe ('SAM_expired1') of DUNS to query for registration information: 

`import json
import requests
import os
import pandas as pd
import numpy as np

payload = SAM_expired1
url = 'https://api.data.gov/sam/v8/registrations/1459697830000?api_key={{SAM_key}}'
SAM_KEY = '[insert api_key here]'

https://api.data.gov/sam/v3/registrations?qterms=duns:(payload)&api_key=SAM_KEY
response = requests.get(url, params=payload)

sam_data = json.loads(response.text)
sam_data
`
