### ISSUE TITLE
Not getting individuals in results

### ISSUE THREAD

**Issue by jlscharf** [GSA/sam_api#136]
Hello, is the API supposed to return only entities with DUNS? I need it to return individuals as well, but as far as I can tell, it isn't. Thanks.

**Comment by aromero6** [comment]
Hello,  yes, you are correct that it will only return entities with DUNS.  If you need individual information, it would be best to use the SAM WebService.  Please see the documentation available here:  http://gsa.github.io/openIAE/developer_resources/Using_SAM_web_services/

This page offers instruction on how to get that setup and use our web services for multiple search option for individuals as well.

Thank you!

**Comment by jlscharf** [comment]
Thanks very much for the information!
