### ISSUE TITLE
"SBA Business Type" AND "NAICS_Exception"

### ISSUE THREAD

**Issue by ChrisWagner214** [GSA/sam_api#47]
The SAM Public Entity Management data extract provides "SBA Business Type" and  "NAICS_Exception", yet the SAM API does not.  Any ideas?  Note:  "SBA Business Type" is NOT the same as "Business Type".  These have different meanings and are exclusive.

Thanks.

**Comment by ChrisWagner214** [comment]
@pammiller0 Can you look into this?

**Comment by pammiller0** [comment]
@ChrisWagner214 and @kaitlin in version 2 (https://api.data.gov/sam/v2/registrations/) of the SAM API, if you search for a registration that has a NAICS with an Exception, the Exception is noted in the JSON with the Tag "ExcpCounter". Here is a link to the field documentation https://gsa.github.io/sam_api/sam/SAMAPI_FieldReferences_v2.xls. Shortly we will be posting more information on the two versions of the API.

**Comment by ChrisWagner214** [comment]
Any word on the "SBA Business Types" component of the data?  I don't see any reference to that in the spreadsheet referenced above.

**Comment by pammiller0** [comment]
SBA Business Types 8A Joint Venture and Hub Zone will be available in the June sam.gov release. @ChrisWagner214 @kaitlin we answered NAICS exception and various other posts are covering the SBA Business Types. Can you close this one? :)

**Comment by kaitlin** [comment]
Yes, it seems the SBA business type issue is covered in #39 and #41. I will close this for now since the NAICS exception issue seems to be resolved. Thanks @pammiller0 !
