### ISSUE TITLE
Error 429 - Too many requests

### ISSUE THREAD

**Issue by ChrisWagner214** [GSA/sam_api#51]
Can you please describe the logic that triggers this error message in the SAM API?

The remote server returned an error: (429) Too Many Requests.

I ask as I ran a batch or data yesterday around noon time, and then tried another batch this morning at 2:00 AM and received 3899 error 429 messages.

My question is:  Is this limit based on a DAILY limit, or a sliding 24 hour window of time?  The documentation (SAM API web site) indicates that this is a DAILY limit.

From the SAM API site:

"A couple basic notes: the rate limits for the API are currently 5,000 calls/day and 5 calls per 5 seconds. As we go forward and understand the impact of usage of the API on SAM, we will adjust the limits accordingly as well as allow for individual users with specific needs to have customized rate limits appropriate to their use."

My results form requesting data at 2:00 AM this morning:

Success:  (731 requests)
The remote server returned an error: (500) Internal Server Error.  (211 requests)
The remote server returned an error: (403) Forbidden. (88 requests)
The remote server returned an error: (404) Not Found. (71 requests)
The remote server returned an error: (429) Too Many Requests.  (3899 requests)

Total:  5000 Requests for day of 1/8/2015.  Should this be INDEPENDENT of any requests done on 1/7/2015? If not, can you please describe the logic that limits the requests so I can code accordingly?

Thank you.

Chris Wagner

**Comment by nvembar** [comment]
Hmm... We actually don't raise the 429 error ourselves, we rely on api.data.gov to do our rate limiting. That's probably coming from there and I can't necessarily say how that happens. If we have to correct our documentation, we'll do so... 

Lemme find out about that part of this.

**Comment by GUI** [comment]
The 429 rate limits are indeed coming from api.data.gov's rate limits. The api.data.gov rate limits are based on a sliding 24 window, rather than a hard reset at midnight. So you're receiving the error because you've made more than 5,000 requests in the past 24 hours with that API key. This documentation on [Understanding Rate Limit Time Periods](http://api.data.gov/docs/rate-limits/#understanding-rate-limit-time-periods) gives some examples of how the sliding time windows work, that should hopefully help explain it. You may also be interested in [How Do I See My Current Usage](http://api.data.gov/docs/rate-limits/#how-do-i-see-my-current-usage) info on that same page. You might be able to use that information you get on every response to better throttle your requests.

Does that help clear things up? If not, let us know.

**Comment by GUI** [comment]
Also, I submitted a small pull request to update the documentation on the SAM docs so that it reads per 24 hours, instead of per day to hopefully help clarify this: https://github.com/GSA/sam_api/pull/55

**Comment by ChrisWagner214** [comment]
Thank you very much.  That definitely clears things up.

Please keep this issue open until the documentation on the SAM API site
is corrected so it is not forgotten.

Thanks!

**Comment by ChrisWagner214** [comment]
Can you also confirm the 1 request per second rate?  I had to back down to include a 2.25 second delay to also eliminate this error.

Thanks!

**Comment by GUI** [comment]
Yes, the 5 requests per 5 seconds is correct for the SAM API. In looking at our logs, I can't find where you were running into that limit, but I might be missing it. But on a quick test, I was able to confirm I didn't get any rate limit errors with a 1 second sleep between requests: https://gist.github.com/GUI/4898ee03d7b2d487ed05

If you are getting rate limit errors with your requests throttled to 1 per second (and assuming you're not running into your 24 hour limit), can you let me know the exact time frame you encountered those at?

**Comment by ChrisWagner214** [comment]
I'll run a quick set now with throttle set to 1000ms between requests.

Give me a few minutes and I will respond again with status.

Thanks!

**Comment by ChrisWagner214** [comment]
I was able to do a quick pass and didn't get any timeouts on this pass. 
Are you able to inspect logs for the error 500 messages?

[LastFailureDate] shown below is the timestamp to look for.  [Duns13] is
that data that was being requested.

Thanks!

ID    Duns13    FirstFailureDate    LastFailureDate   
LastFailureMessage    Attempts    SuccessDate
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
805    0044823780000    2015-01-08 14:42:25.183    2015-01-08
14:42:25.183    The remote server returned an error: (500) Internal
Server Error.    1    NULL
806    0273973190000    2015-01-08 14:42:27.743    2015-01-08
14:42:27.743    The remote server returned an error: (500) Internal
Server Error.    1    NULL
807    1486878950000    2015-01-08 14:53:48.137    2015-01-08
14:53:48.137    The remote server returned an error: (403) Forbidden.   
1    NULL
808    0906108950000    2015-01-08 14:53:50.617    2015-01-08
14:53:50.617    The remote server returned an error: (403) Forbidden.   
1    NULL
809    0045071430000    2015-01-08 14:53:53.143    2015-01-08
14:53:53.143    The remote server returned an error: (500) Internal
Server Error.    1    NULL
810    0101236930000    2015-01-08 14:53:54.500    2015-01-08
14:53:54.500    The remote server returned an error: (403) Forbidden.   
1    NULL
811    0516208960000    2015-01-08 14:53:55.807    2015-01-08
14:53:55.807    The remote server returned an error: (500) Internal
Server Error.    1    NULL
812    7876265140000    2015-01-08 14:53:59.560    2015-01-08
14:53:59.560    The remote server returned an error: (500) Internal
Server Error.    1    NULL
813    8351124180000    2015-01-08 14:54:00.657    2015-01-08
14:54:00.657    The remote server returned an error: (404) Not Found.   
1    NULL
814    8593288180000    2015-01-08 14:54:13.287    2015-01-08
14:54:13.287    The remote server returned an error: (404) Not Found.   
1    NULL
815    8330450600000    2015-01-08 14:54:14.547    2015-01-08
14:54:14.547    The remote server returned an error: (500) Internal
Server Error.    1    NULL
816    8062432960000    2015-01-08 14:54:17.250    2015-01-08
14:54:17.250    The remote server returned an error: (403) Forbidden.   
1    NULL
817    0013680830000    2015-01-08 14:54:19.937    2015-01-08
14:54:19.937    The remote server returned an error: (500) Internal
Server Error.    1    NULL
818    5202439920000    2015-01-08 14:54:21.043    2015-01-08
14:54:21.043    The remote server returned an error: (404) Not Found.   
1    NULL
819    2970617360000    2015-01-08 14:54:22.117    2015-01-08
14:54:22.117    The remote server returned an error: (404) Not Found.   
1    NULL
820    8246237710000    2015-01-08 14:54:23.190    2015-01-08
14:54:23.190    The remote server returned an error: (404) Not Found.   
1    NULL
821    7831403820000    2015-01-08 14:54:28.143    2015-01-08
14:54:28.143    The remote server returned an error: (500) Internal
Server Error.    1    NULL
822    0011418030000    2015-01-08 14:54:29.497    2015-01-08
14:54:29.497    The remote server returned an error: (500) Internal
Server Error.    1    NULL
823    0092135960000    2015-01-08 14:54:30.763    2015-01-08
14:54:30.763    The remote server returned an error: (500) Internal
Server Error.    1    NULL
824    9639954850000    2015-01-08 14:54:35.683    2015-01-08
14:54:35.683    The remote server returned an error: (500) Internal
Server Error.    1    NULL
825    8795237020000    2015-01-08 14:54:38.213    2015-01-08
14:54:38.213    The remote server returned an error: (500) Internal
Server Error.    1    NULL
826    8479394690000    2015-01-08 14:54:39.583    2015-01-08
14:54:39.583    The remote server returned an error: (500) Internal
Server Error.    1    NULL
827    8584806500000    2015-01-08 14:54:40.800    2015-01-08
14:54:40.800    The remote server returned an error: (500) Internal
Server Error.    1    NULL
828    9339691230000    2015-01-08 14:54:42.360    2015-01-08
14:54:42.360    The remote server returned an error: (500) Internal
Server Error.    1    NULL
829    9615829830000    2015-01-08 14:54:44.893    2015-01-08
14:54:44.893    The remote server returned an error: (500) Internal
Server Error.    1    NULL
830    9617605630000    2015-01-08 14:54:46.217    2015-01-08
14:54:46.217    The remote server returned an error: (500) Internal
Server Error.    1    NULL
831    0419184210000    2015-01-08 14:54:50.113    2015-01-08
14:54:50.113    The remote server returned an error: (500) Internal
Server Error.    1    NULL
832    0508511790000    2015-01-08 14:54:51.370    2015-01-08
14:54:51.370    The remote server returned an error: (500) Internal
Server Error.    1    NULL
833    0212193400000    2015-01-08 14:54:52.607    2015-01-08
14:54:52.607    The remote server returned an error: (500) Internal
Server Error.    1    NULL
834    0051278290000    2015-01-08 14:54:55.097    2015-01-08
14:54:55.097    The remote server returned an error: (500) Internal
Server Error.    1    NULL
835    1511836960000    2015-01-08 14:54:57.600    2015-01-08
14:54:57.600    The remote server returned an error: (500) Internal
Server Error.    1    NULL

**Comment by pammiller0** [comment]
Hi Chris,


http://gsa.github.io/sam_api/sam/basics.html  has the changes to the
documentation for the rate limits in concurrence for #51. That is why we
closed it.



Thanks,
Pam

On Sun, Jan 25, 2015 at 11:35 PM, Chris Wagner <notifications@github.com>
wrote:

> Closed #51 <https://github.com/GSA/sam_api/issues/51>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GSA/sam_api/issues/51#event-224469201>.
>



-- 

pamela.miller@gsa.gov
(202) 694-2958
Check us out at: http://gsa.github.io/openIAE/
