### ISSUE TITLE
Disaster response object in API response.

### ISSUE THREAD

**Issue by ChrisWagner214** [GSA/sam_api#52]
This is not documented in the API.

This response provides a "Type" attribute, and an array or area codes.  Can you provide some information on expected responses for TYPE and how this relates to the array of area codes that are also returned?

Thanks.

**Comment by nvembar** [comment]
We're generally using the the disaster relief type as it comes out of the data dictionary [here](https://github.com/GSA/IAE-Architecture/blob/master/as-is/tech-docs/SAM/SAM%20Functional%20Data%20Dictionary%20v4.0.pdf?raw=true). So, that means have "MSA" for a Metropolitan Statistical Area, "CTY" for county, "STA" for state, and "ANY" for, well, any. 

The geographic area codes will correspond to those - the array will identify counties, MSAs or states.

The dictionary is more complete....

**Comment by ChrisWagner214** [comment]
Please re-open

This is what is have encountered for disaster relief [Type]

Select Case UCase(Trim(obj_API_Vendor.DisasterRelief.type))
                        Case "ONE STATE"
                        Case "MULTIPLE STATES"
                        Case Else
                            MsgBox(sz_Type)
                    End Select

This is NOT documented, and is independent of the array of area codes documented on page 22 and 23.

Please advise.
