### ISSUE TITLE
CongressionalDistrict field.

### ISSUE THREAD

**Issue by ChrisWagner214** [GSA/sam_api#54]
Seeing many nulls in this field.  This seems to always be populated when pulling data from FPDS Atom feed, but sparsely populated when requesting from the SAM API.

**Comment by nvembar** [comment]
Strange... not sure why that would be true.

**Comment by ChrisWagner214** [comment]
This is from one of my test passes of data:

[SAM_Congressional_District]	[Records]
NULL	818
0	40
1	1
2	1
3	1
4	2
8	4
12	1
14	1
98	24

**Comment by nvembar** [comment]
In this breakdown, do you know if those entries without Congressional District are generally expired or are they active?

If they're expired, they're not necessarily going to have a CD

**Comment by ChrisWagner214** [comment]
they are probably all expired, but should that matter? if so, why would expired records report congressional district differently.

Thanks.

**Comment by nvembar** [comment]
Expired records were migrated from CCR - they didn't require or calculate CD as a field back then, so it's not populated now.So, old data and current calculations wouldn't reflect accurate CDs.

**Comment by ChrisWagner214** [comment]
I can understand this.  Would the Congressional district (as it comes from the ATOM API) be a more accurate field to use then?  Thanks.

**Comment by nvembar** [comment]
The CD from SAM will be accurate for any active entities. I'd supplement it with the ATOM feed if not present in SAM.

**Comment by ChrisWagner214** [comment]
Perfect!  Thank you!
