### ISSUE TITLE
doingbusinessasName:  JSON constructed as an array for DUNS 1063777370000

### ISSUE THREAD

**Issue by ChrisWagner214** [GSA/sam_api#60]
Please check json construction methodology.  When requesting duns 1063777370000, the result for  doingBusinessAsName property is being returned as an array.

    "doingBusinessAsName":[  
            "FORMERLY INFOCUS VIDEO",
            "INC."
         ], 

Other DUNS records were processing fine, just one is different for some reason.

Thanks.

**Comment by nvembar** [comment]
Thanks for the catch. @Rafael-IBM

**Comment by pammiller0** [comment]
@ChrisWagner214 for that record, the DBA field had a data anomaly,  two brackets "[ ]". That is what caused it to be returned as an array.

**Comment by pammiller0** [comment]
@ChrisWagner214 Hey Chris. We are checking into to seeing if the vendor entered in the brackets or if it is data that was migrated over from the legacy CCR system.

**Comment by pammiller0** [comment]
Update- this particular record was migrated over from the legacy CCR system. We have taken the brackets out of this DUNS so it will no longer be returned as an array. @ChrisWagner214 can we close this one?

**Comment by ChrisWagner214** [comment]
Has this field been searched in the database for other occurrences so
this is corrected for all instances?  If so, then the issue can be
closed, otherwise the problem will reoccur.  To be corrected properly,
the field should be searched for any occurrence of [ or ] and have that
character removed.

Thanks.

**Comment by pammiller0** [comment]
Yes there were 6 instances of this in total and we have cleaned out the brackets on all 6. Thanks!

**Comment by ChrisWagner214** [comment]
Done!   Thank you very much!
