### ISSUE TITLE
Outdated references to upcoming search api 

### ISSUE THREAD

**Issue by gbinal** [GSA/sam_api#62]
It looks like there's at least one place (['Coming Soon' on the basics page](http://gsa.github.io/sam_api/sam/basics#coming-soon), maybe more, where the search API is still referenced as being in the future.  But that [appears to be out of date](http://gsa.github.io/sam_api/sam/search.html).

I'm happy to take a first pass at a pull request at this but recommend other eyes give it a pass.

**Comment by gbinal** [comment]
Here's a first pass -https://github.com/GSA/sam_api/pull/63

**Comment by aromero6** [comment]
Gray, looks like Navin merged your changes and all the information has been updated.  Thanks!
