### ISSUE TITLE
Call to test - Intermittent 500s

### ISSUE THREAD

**Issue by aromero6** [GSA/sam_api#77]
Good morning everyone!

In researching the intermittent 500 errors we have come to a realization that there is an issue with the database and its performance.  We would like to setup an online session with you the testers and our dev team at IBM to go over specifics and perform live testing against the system.

This session would be Wednesday afternoon at 3pm EST.  The link to join the session is:

https://meet.gsa.gov/virtualization

Once you bring up the page, login as guest and the system will instruct you to enter your phone number so it may call you to join the voice part of the session.

Before the meeting if you can please provide the following information:
1. A list of DUNS that are failing during your testing
2. Any external software that you are utilizing to make the API calls
3. What is the frequency and rate of your API calls
4. Are you calling the same DUNS within a second of each other
5. Any other specific anomalies regarding the 500 error

Thank you and hope to see you at the online testing session.
Tony

**Comment by aromero6** [comment]
@kaitlin 
@ChrisWagner214
@dwcaraway

**Comment by kaitlin** [comment]
@aromero6 Hi Tony. Has the IBM team performed any automated load testing? If so, can you share the results?

**Comment by aromero6** [comment]
@Rafael-IBM  Rafael, do you guys have any results from automated load testing or any testing results you guys may have performed?

Also....  To everyone, the session has been moved to 4/23 -  3pm EST.  Please submit any information here before 4/21 please.

Thanks,
Tony

**Comment by Rafael-IBM** [comment]
We have not run a full automated testing on API.  We have scripts available for load testing, but it has been applied more to testing functionality.  We can certainly discuss what and how to test to accurately affect real-world use cases.

**Comment by kaitlin** [comment]
@Rafael-IBM @aromero6  It seems like automated load testing will be better able to flesh out and uncover the source of the database congestion than 4-5 users looking at the API at the same time. Rather than looking at the number of requests per second your top users generate, I would recommend picking a number of RPS that you want to support, and test-fix-repeat until you reach that benchmark.

**Comment by ChrisWagner214** [comment]
What exactly do error 500 messages mean?

Is this error message a "catch all" for any type of system error, or an
an indicator of a specific error?  Can you provide some details as we
may be able to isolate conditions to avoid this error?

I ask as I have reduced my query rate to delay 2000ms between each API
call, but still get these errors do I don't think it is a timing thing
on my end.  One note although, just about all the records that I am
requesting via the API are EXPIRED registrations as I can't get the
older ones from the file extracts.  Even though I am requesting older
records, I don't believe they should cause errors.  If this is a wrong
assumption, please let me know.

I would recommend looking at your underlying database on these DUNS
provided below and checking on your process that pulls these records.  I
am guessing that these records contain unexpected data, causing the
issue.  Could be embedded commas, JSON reserved characters, NULL fields
or something, but I am seeing repeatable error 500 messages which leads
me to believe it is data related and not timing or system load related. 
All that I can do is make assumptions as I am a consumer of this API and
do not have access to any system that hosts the API or it's source code.

(Will the source code for the API be placed on gitHub for public review?
- This could help as I am assuming that this is taxpayer funded.)

Also, I am generating these API requests from a Microsoft .NET app that
I have provided source code for examination earlier.

Below are the last 25 errors with duns and timing details (sorted by
last failure date descending)

Duns13    LastFailureDate    LastFailureMessage
9306122880000    2015-04-13 18:01:04.473    The remote server returned
an error: (500) Internal Server Error.
0032470950000    2015-04-13 18:01:02.337    The remote server returned
an error: (500) Internal Server Error.
6242216930000    2015-04-13 18:01:00.137    The remote server returned
an error: (500) Internal Server Error.
0372988330000    2015-04-13 18:00:57.937    The remote server returned
an error: (500) Internal Server Error.
1394867160000    2015-04-13 18:00:55.753    The remote server returned
an error: (500) Internal Server Error.
1391285600000    2015-04-13 18:00:53.553    The remote server returned
an error: (500) Internal Server Error.
8485836260000    2015-04-13 18:00:51.383    The remote server returned
an error: (500) Internal Server Error.
0405687840000    2015-04-13 18:00:49.217    The remote server returned
an error: (500) Internal Server Error.
1291542200000    2015-04-13 18:00:47.047    The remote server returned
an error: (500) Internal Server Error.
1075219650000    2015-04-13 18:00:44.833    The remote server returned
an error: (500) Internal Server Error.
8053213530000    2015-04-13 18:00:42.617    The remote server returned
an error: (500) Internal Server Error.
9298332590000    2015-04-13 18:00:40.433    The remote server returned
an error: (500) Internal Server Error.
7868143680000    2015-04-13 18:00:38.233    The remote server returned
an error: (500) Internal Server Error.
1572344280000    2015-04-13 18:00:35.987    The remote server returned
an error: (500) Internal Server Error.
1299306400000    2015-04-13 18:00:33.770    The remote server returned
an error: (500) Internal Server Error.
9327478010000    2015-04-13 18:00:31.527    The remote server returned
an error: (500) Internal Server Error.
0420354850000    2015-04-13 18:00:28.843    The remote server returned
an error: (500) Internal Server Error.
1450596760000    2015-04-13 18:00:26.673    The remote server returned
an error: (500) Internal Server Error.
0679254900000    2015-04-13 18:00:24.490    The remote server returned
an error: (500) Internal Server Error.
1445476630000    2015-04-13 18:00:22.353    The remote server returned
an error: (500) Internal Server Error.
0765810080000    2015-04-13 18:00:20.247    The remote server returned
an error: (500) Internal Server Error.
0764720960000    2015-04-13 18:00:18.030    The remote server returned
an error: (500) Internal Server Error.
7859495380000    2015-04-13 18:00:15.893    The remote server returned
an error: (500) Internal Server Error.
1067266360000    2015-04-13 18:00:13.647    The remote server returned
an error: (500) Internal Server Error.
9567838230000    2015-04-13 18:00:11.463    The remote server returned
an error: (500) Internal Server Error.

**Comment by ChrisWagner214** [comment]
@kaitlin  Please review my prior post here on github to ensure it gets to the proper people.  I forgot to @copy you so you get the email notification.    Just trying to help get this one resolved as it will help all involved. 

Thanks.

**Comment by seanherron** [comment]
@Rafael-IBM Have you done any access/error log analysis on the web application? You should be able to determine to some extent the load characteristics based on `200 OK` access results vs `500` error results logged by the webserver.

**Comment by ChrisWagner214** [comment]
@aromero6 I was not able to attend call today.  Can you please post any findings or highlights of the call today so we understand what is being done to resolve the error 500 error messages?  Thank you.

**Comment by aromero6** [comment]
Hi Chris @ChrisWagner214,
Unfortunately there was not a great turnout for the call.  But based on the information you presented and some additional testing, we were able to resolve what the reasoning is behind the 500 error and why someone would receive it.  The explanation which we were able to come up with based on different testing scenarios is:
500 - 	Internal error **NOT PERFORMANCE ISSUE**
		Reasons for why this error message is thrown
		1) Generic Technical Error that the API team should research
		2) Due to a Program/Technical/System exception
		3) Examples are Parsing, Null Pointer, SQL exceptions 

That being said, the dev team is working on a way of classifying the errors in a future release to give "Friendly Names" that are more descriptive to explain why the user is receiving the 500 error.

I hope this helps.  

I will leave this Issue open for another week and if we still have questions, please post them here.  If there are no other discussions, I will close out this issue at that time.

Thanks,
Tony

**Comment by ChrisWagner214** [comment]
Please leave the issue OPEN until the correction is released and in
production.

Thank you.

**Comment by aromero6** [comment]
@ChrisWagner214 ,

Sorry, let me clarify, by close this issue, I mean issue #77 specifically, which is just the call to test.  The original issue #19 will remain open until the new release is out and we can confirm that the friendly names are in place.

Thanks,
Tony

**Comment by ChrisWagner214** [comment]
Perfect!  Thank you.

**Comment by aromero6** [comment]
Closing this issue as it was just a call to test.  Original issue remains open until new release verifies that it fixes the issue.

Thanks,
Tony
