### ISSUE TITLE
Possible to query historical data?

### ISSUE THREAD

**Issue by micahsaul** [GSA/sam_api#79]
I'm trying to validate historical data against SAM and was wondering if there is a way to query the API with an "as of date"?

**Comment by aromero6** [comment]
Micah,

I will ask the development team and get back to you as soon as I find an
answer.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Enterprise Infrastructure
O: 312.353.3116
C: 312.497.5592

**Comment by aromero6** [comment]
Micah,

The SAM Search API will be able to search by date in the June Release (June
26).  More documentation will be loaded to the GitHub site to explain
functionality and enhancements within the next week.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Enterprise Infrastructure
O: 312.353.3116
C: 312.497.5592

**Comment by micahsaul** [comment]
Great! Thanks for the update!
