### ISSUE TITLE
How current is the data retrieved via Web services vs the SAM Web site?

### ISSUE THREAD

**Issue by saintcyr** [GSA/sam_api#88]
I understand that previously that ws data could be 24 hours or possibly more. Is it now "live?"

**Comment by aromero6** [comment]
@saintcyr

Our support team verified the following:

SAM Entity Management web services (which is typically what we refer to
when they say 'web services') - is NOT realtime. We update the database
view 4AM and 4PM - so it is based on that. It is new as of the most recent
view update.

SAM Exclusion Search web service (Exclusions) is real-time. Once that
exclusion is activated in SAM, you can find it. Direct DB query vs DB view
for Entity web services.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Enterprise Infrastructure
O: 312.353.3116
C: 312.497.5592
