### ISSUE TITLE
Getting XML Deserialization Error calling doSearch in .NET

### ISSUE THREAD

**Issue by vericon** [GSA/sam_api#93]
I am getting the following error when the ExclusionSearchResponseType object has a value for excludedEntity:

There is an error in XML document (1, 1426).

Stack Trace: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle) at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall) at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters) at ExclusionSearchServiceBeanService.doSearch(OperationSearchType exclusionSearchCriteria) at FTIntegrations.EPLS.PerformSearch(ApplicantService appService) 

When there are no records found the search completes without issue. 

Am I doing something wrong?

Thanks,

Tony Pichetto
Director of IT/Operations
Vericon Resources, Inc.

**Comment by aromero6** [comment]
Good morning Tony,

I have sent this information to our technical team.  When I receive a
response, I will update you and let you know what is happening.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Enterprise Infrastructure
O: 312.353.3116
C: 312.497.5592

**Comment by vericon** [comment]
Hi Tony,
 When should I expect a response?  We are currently unable to complete searches with records through the integration.

Thanks,

Tony Pichetto

**Comment by GreigFields** [comment]
Hi Tony, Not sure if you heard back from Antonio, but the problem seems to be that the XML returned from SAM sometimes contains a null or even "text" in the date fields, and when Null values are contained in date fields the XMLSerializer throws an error.  I think the best approach is to modify the Reference.cs file associated with the web Reference or Service Reference you created by changing all the date fields to strings in the ExclusionActionType Class. This seemed to fix most of the errors. The only issue is that you have to convert the strings to datetime after you get the ExclusionSearchResponseType results structure if you need them in that format. 
Hopefully this helps.

Here's the modified ExclusionActionType class, I left the old code commented out so you could see the approach. 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sam.gov")]
    public partial class ExclusionActionType : ExclusionValueObjectType {
        
        // private System.Nullable<System.DateTime> createDateField;
        private string createDateField;

        private bool createDateFieldSpecified;
        
        //private System.Nullable<System.DateTime> updateDateField;
        private string updateDateField;

        private bool updateDateFieldSpecified;

        // private System.Nullable<System.DateTime> activeDateField;
        private string activeDateField;

        private bool activeDateFieldSpecified;
        
        private string actionStatusField;
        
        private string agencyComponentField;

        private System.Nullable<System.DateTime> termDateField;
        //private string termDateField;

        private bool termDateFieldSpecified;
        
        private string termTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        // public System.Nullable<System.DateTime> createDate {
        public string createDate
        {

            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        // public System.Nullable<System.DateTime> updateDate {
        public string updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        // public System.Nullable<System.DateTime> activeDate {
        public string activeDate {
            get {
                return this.activeDateField;
            }
            set {
                this.activeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeDateSpecified {
            get {
                return this.activeDateFieldSpecified;
            }
            set {
                this.activeDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string actionStatus {
            get {
                return this.actionStatusField;
            }
            set {
                this.actionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string agencyComponent {
            get {
                return this.agencyComponentField;
            }
            set {
                this.agencyComponentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        // public System.Nullable<System.DateTime> termDate {
        public System.Nullable<System.DateTime> termDate {
            get {
                return this.termDateField;
            }
            set {
                this.termDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool termDateSpecified {
            get {
                return this.termDateFieldSpecified;
            }
            set {
                this.termDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string termType {
            get {
                return this.termTypeField;
            }
            set {
                this.termTypeField = value;
            }
        }
    }

**Comment by vericon** [comment]
Hi Greg,
 Thanks for posting!  I didn't hear back from Antonio, but this is exactly how we resolved the issue, and I've been meaning to log back in and post the solution.  

I was hoping the GSA would fix their code so we wouldn't have to use a workaround, but for now this will have to do.

Cheers,

Tony Pichetto
Director of IT/Operations
Vericon Resources, Inc.

**Comment by GreigFields** [comment]
That's Great Tony!, Should this be closed now???
