### ISSUE TITLE
customized rate limits

### ISSUE THREAD

**Issue by roncarter** [GSA/sam_api#95]
http://gsa.github.io/sam_api/sam/index.html

Wondering if this was ever addressed for users requiring customized rate limits?

Please note: the rate limits for the API are currently 5,000 calls per 24 hours and 5 calls per 5 seconds. As we go forward and understand the impact of usage of the API on SAM, we will adjust the limits accordingly as well as allow for individual users with specific needs to have customized rate limits appropriate to their use.

**Comment by aromero6** [comment]
Hi,

Yes, we are able to provide customized rate limits for people that show a
need and it is done on a limited time basis.  After the time the limit has
been requested for has passed, it will return to the standards rate limits.

If a customized limit is needed, please email me directly at
antonio.romero@gsa.gov

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Enterprise Infrastructure
O: 312.353.3116
C: 312.497.5592

**Comment by roncarter** [comment]
Hi Tony, 

Thanks for your prompt reply! Our company is working closely with Colorado Procurement Technical Assistance Center (PTAC. Our goal is to point people toward sam.gov and at the same time provide maximum information to PTAC and their clients from our web site. 

Our need is to down load specific information from all sam.gov registrants and then only update daily after that. Is it possible to allow our current API key chBaI3oEfNvWvJaExigPikjwk4oDnnKMRqaP9cGC unlimited calls until task is complete or could we use more than one key for a shorter period time. Please advise what you think the best way so we don't abuse the system. 

Thanks for you consideration to this request. 


Regards, 
Ron Carter 
BWISEBGREEN 
roncarter@bwisebgreen.com 
719 337-1078 

----- Original Message -----
