### ISSUE TITLE
SAM Exclusions Extract Data Package - automated download fails

### ISSUE THREAD

**Issue by mrgrita** [GSA/sam_api#99]
I have a .net 4.0 console application that downloads the SAM Exclusions List file using a simple HttpWebRequest download process. This has been working for years and now for my July 2016 download the process failed. I tried troubleshooting on my end, but I keep getting the same error message: "HTTPS handshake to www.sam.gov failed. System.IO.IOException Authentication failed because the remote party has closed the transport stream." 

I am using the following url: https://www.sam.gov/public-extracts/SAM-Public/SAM_Exclusions_Public_Extract_xxxxx.ZIP where the xxxxx is changed at runtime to retrieve the previous day's file.

My code is as follows:

WebClient _myWebClient = new WebClient();
 _myWebClient.UseDefaultCredentials = true; 
ServicePointManager.DefaultConnectionLimit = int.MaxValue;   
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;
AcceptAllClientCertificates();
_myWebClient.DownloadFile(fileURL, targetURL);

I use the same code to download the OIG LEIE file successfully, so I do not feel there is a problem on my end.

Has anything changed on the server preventing me from downloading this file?

**Comment by aromero6** [comment]
Good morning,

I have a distinct possibility that this might be related to the upgrade to
TLS 1.2 and the removal of 1.0.  Have you tried to get the new SSL
certificates from the SAM servers?

I will also pass this on to our technical team to see if they have any
other ideas.

Thanks,
Tony


Antonio Romero
US Federal Government
General Services Administration OCIO
Office of Enterprise Infrastructure
O: 312.353.3116
C: 312.497.5592

**Comment by mrgrita** [comment]
I had to upgrade my application to .Net 4.6.1 to use TLS 1.2 and that worked for me.  .Net 4.0 only has TLS 1.0 available. Thank you for your prompt reply.
